"""first migarte

Revision ID: a61392577911
Revises: 
Create Date: 2023-09-25 00:11:56.888105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61392577911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_map', 'short',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_map', 'short',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
